//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controls/DebugKeys.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DebugKeys: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DebugKeys()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DebugKeys"",
    ""maps"": [
        {
            ""name"": ""ExtraHUD"",
            ""id"": ""6af5b21f-fd9a-4c97-b6d3-bba7244720a3"",
            ""actions"": [
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""4017f790-e0c5-40eb-acc7-6543b7246e69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""11325bfc-3d64-417e-9808-fd30c441bba0"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ExtraHUD
        m_ExtraHUD = asset.FindActionMap("ExtraHUD", throwIfNotFound: true);
        m_ExtraHUD_Toggle = m_ExtraHUD.FindAction("Toggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ExtraHUD
    private readonly InputActionMap m_ExtraHUD;
    private List<IExtraHUDActions> m_ExtraHUDActionsCallbackInterfaces = new List<IExtraHUDActions>();
    private readonly InputAction m_ExtraHUD_Toggle;
    public struct ExtraHUDActions
    {
        private @DebugKeys m_Wrapper;
        public ExtraHUDActions(@DebugKeys wrapper) { m_Wrapper = wrapper; }
        public InputAction @Toggle => m_Wrapper.m_ExtraHUD_Toggle;
        public InputActionMap Get() { return m_Wrapper.m_ExtraHUD; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ExtraHUDActions set) { return set.Get(); }
        public void AddCallbacks(IExtraHUDActions instance)
        {
            if (instance == null || m_Wrapper.m_ExtraHUDActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ExtraHUDActionsCallbackInterfaces.Add(instance);
            @Toggle.started += instance.OnToggle;
            @Toggle.performed += instance.OnToggle;
            @Toggle.canceled += instance.OnToggle;
        }

        private void UnregisterCallbacks(IExtraHUDActions instance)
        {
            @Toggle.started -= instance.OnToggle;
            @Toggle.performed -= instance.OnToggle;
            @Toggle.canceled -= instance.OnToggle;
        }

        public void RemoveCallbacks(IExtraHUDActions instance)
        {
            if (m_Wrapper.m_ExtraHUDActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IExtraHUDActions instance)
        {
            foreach (var item in m_Wrapper.m_ExtraHUDActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ExtraHUDActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ExtraHUDActions @ExtraHUD => new ExtraHUDActions(this);
    public interface IExtraHUDActions
    {
        void OnToggle(InputAction.CallbackContext context);
    }
}
